#' Render an attrition table as HTML with KableExtra
#'
#' Renders a formatted attrition table using `kableExtra`.
#'
#' @param attrition_table A data.frame generated by `generate_attrition_table()`.
#' @param full_width Logical. Should the table span the full width? (default: TRUE)
#' @param bootstrap_options Character vector of Bootstrap styling options. Default: c("striped", "bordered").
#' @param caption Character. Caption text to display above the table. Default is NULL.
#' @param footnotes Optional character vector of additional footnotes.
#'
#' @return An HTML table rendered via `kableExtra`.
#' @examples
#'\dontrun{
#'  render_attrition_table(
#'    attrition_table = attrition_table,
#'    full_width = FALSE,
#'    bootstrap_options = c("striped", "hover"),
#'    caption = "Table 1: Study Attrition"
#'  )
#'}
#' @export
render_attrition_table <- function(attrition_table,
                                   full_width = TRUE,
                                   bootstrap_options = c("striped", "bordered"),
                                   caption = "Table 1: Study Attrition",
                                   footnotes = NULL) {

  # Input validation
  checkmate::assert_data_frame(attrition_table, min.rows = 1)
  checkmate::assert_character(bootstrap_options, min.len = 1)
  checkmate::assert_flag(full_width)
  checkmate::assert_string(caption, null.ok = TRUE)
  checkmate::assert_character(footnotes, null.ok = TRUE)

  # Total patients value for footnote
  total_patients <- attrition_table$col1[1]

  # Combine footnotes
  numbered_footnotes <- c(
    glue::glue("All percentages use N = {total_patients} as the denominator."),
    footnotes
  )

  attrition_table %>%
    dplyr::select(-critnum) %>%
    kableExtra::kable(
      col.names = c("Criteria",
                    "Patients Included (N)",
                    "Patients Included (%)",
                    "Patients Excluded (N)",
                    "Patients Excluded (%)"),
      align = c('l', 'r', 'r', 'r', 'r'),
      booktabs = TRUE,
      caption = caption
    ) %>%
    kableExtra::kable_styling(
      bootstrap_options = bootstrap_options,
      full_width = full_width,
      fixed_thead = T
    ) %>%
    kableExtra::footnote(
      general = "Final sample used for primary analysis.",
      number = numbered_footnotes
    )
}
